language: go
go_import_path: github.com/osbkit/minibroker
go:
- 1.10.x
sudo: required
services:
- docker
env:
  global:
  # DOCKER_USERNAME
  - secure: LGTBy22cdELa3AhM+BODY1IsuZ2CcIl5A64EJjSl/ynvACoKNCfOwD+ALuk8eqkTPu9RaLflH/QA3UE7bcmVu3Nfmwxv2T/U/YEQaADN+5O2X7aBmL3Ze7jF6FRupYYtwrb+jNl2NOUo2hS0qbx7lyljV3FsM5veR361aiseVYTXmaA0s4MgHQeRHW+VL25zHZ0ZTg6XJKPD1QAslUglAjCa5/fC/XyRvXoFXj5AOwYuHZfdmmQHf3Pnxsg+dLAmF6HoTisz9Oh+YAUOnZZspIPMxC/MZOYxn/XbtG7oqNrtgUVKBEJWTYRp/UoKSrWKWvknjOQXi/dCCtCXyu8TKjn9Z9CbtIMq0DYoxWe8zwf+WZEhMftoLyQohcywYxZf9SiXzZtiJGDuxczPQTz5HB8at+ppxGR5toDyFaGe7a+V8jjhJTnJb2bGO3cpkxwSNjG8HHnuMHofPLLy4hlGp72/3rH2PZho2d8TSe53QqyEawY15xdJlV/4l7WjybO3bslCq1Mw+nBXQjuqwTREJy7BWpEkfUAJV0lqUzi+jkuf1uhvrykVAP015w0jgF9/o0VRUk7lLaglTH1fxSYUohFjHO0z0lpTm62MJnGO1IdRluO0OLWILDwxwIfit0VVjFOaw2d3VM1xmA7cYAaSv+Sauw8E2MUgXqXDmkcXRws=
  # DOCKER_PASSWORD
  - secure: hmFUa0ZC3fPbbf2umWPWYY58n/ABXg2JDO/Mr8BK6hYgLcC2+G5jOJfyxvbXNc/VI4Xb/ErsmX7auZhxIOxbzArjiXGQSVs5j1ocWKrf/Cdl5sdtVIOG2LXBqxAxqGp8pcQEgIDjHjeegJ5rKMGyPpGbpHi9m2MeP1oALWU2qzi2F6FW97ZhMPN0G40kjs9ZLEiWo9WffokH5dwubm/4sXgsfSK+TY2EPh4A3O6MV6FoZ8/0l7MFJ61TT6hzo3Rr913DobWop5rJeap71618+YmhDzgcDaerwyag8jXjGDlJvtiYEMVpdAPsXkcEvk2qBiIMM4e5KPdnS+M61ktn7Q10y1Y0E/U3Yo6mzFPSYkoRa68LZ0G9XIgANs+i42+k6wCEi4UZMIxKv0fn3Gkg0LvibFYBbczKavCSRJOWFXzgv4pxdZVLDQPSlyI0lx+lMdL/yeaScFOuTzQsCLUBPggFebXWmiKGNKjvcGEWf/R7lbnfZ60FedeSEShnrUA/iPQNyfQ9mOoXSLOpttFenhrkZbYSEGHt7QbU7lVY7/96XmW2zzmeU0zNP9/Da7p3yj0PGgLtkBI1+wK7k0JLXueeLLHIXxBaYn7loTxCPHTT1tMck6Dp/d1/gGlp4omzV8H2MoV0fxeynWNNdNyCGVLkz7zfeqNM3Be4JbgEEc0=
  # AZURE_STORAGE_CONNECTION_STRING
  - secure: RYtKJhU3qcSNOEPJW7N1JtUv3zpm7JTfMyvucaOVXEOR9088UXVw9v79vmSERn8L73J6X3rOZA+yemd4RaxhAh4odhAlpIWPGBO3CycG0UUuTOJnGZ7X8CzDiNfBYdpYQ4BSJuaRR6WlsT9qWVCKN5d3IQhSXYTOBheIJQmo+URZ5PazNHfrcg+sWmbj2JFzOMukEpBJ+EHQNpA/Wg8Vp9Aln8PQwckYap8BcvNX/NHIBpNJ5wNuXi/SZ3FOD3UcILVlam1XhRrQXDeO0rDKoKEQsKCbra041SIw+J0/9rROba4EUq+t9dR5LKOFxEL9Qh033xZ6gO8L1YNjYvkl7qh57UVb/+ovqbKvmFviFfqdZfRO1NFD/dHXlsFs2M0GJet8vxySyKuqRMcqUo8Fh7kr8c816Mchi96twpDJcFuQneoQh93hE32Jf7Kv6y3UgLaShcLYx3IQUYjZScJm7kX1fc8Iiw5/Xawmxl31ByR9govuRwPqVGxqNZbyoxQQHk7ck6TsKIB+YNmfUZ+ZdthKpKFcl/IBwwjchVu62d8T2wZepmL2LWBG+/Zn+oZVymhm7+c1e+Tg4o7wad32MgB4HoXooAohkmDLM6v8O1ShMxcQmnVt7eo7Q0oZRN2A0RcSnPTnOTgJ38Nb5SHzeMmu2KsYpbAV1V44GMm+yEE=
script:
- make build test-unit
deploy:
  provider: script
  script: make release
  on:
    branch: master
