language: go
go_import_path: github.com/osbkit/minibroker
go:
- 1.10.x
sudo: required
services:
- docker
env:
  global:
  # DOCKER_USERNAME
  - secure: LGTBy22cdELa3AhM+BODY1IsuZ2CcIl5A64EJjSl/ynvACoKNCfOwD+ALuk8eqkTPu9RaLflH/QA3UE7bcmVu3Nfmwxv2T/U/YEQaADN+5O2X7aBmL3Ze7jF6FRupYYtwrb+jNl2NOUo2hS0qbx7lyljV3FsM5veR361aiseVYTXmaA0s4MgHQeRHW+VL25zHZ0ZTg6XJKPD1QAslUglAjCa5/fC/XyRvXoFXj5AOwYuHZfdmmQHf3Pnxsg+dLAmF6HoTisz9Oh+YAUOnZZspIPMxC/MZOYxn/XbtG7oqNrtgUVKBEJWTYRp/UoKSrWKWvknjOQXi/dCCtCXyu8TKjn9Z9CbtIMq0DYoxWe8zwf+WZEhMftoLyQohcywYxZf9SiXzZtiJGDuxczPQTz5HB8at+ppxGR5toDyFaGe7a+V8jjhJTnJb2bGO3cpkxwSNjG8HHnuMHofPLLy4hlGp72/3rH2PZho2d8TSe53QqyEawY15xdJlV/4l7WjybO3bslCq1Mw+nBXQjuqwTREJy7BWpEkfUAJV0lqUzi+jkuf1uhvrykVAP015w0jgF9/o0VRUk7lLaglTH1fxSYUohFjHO0z0lpTm62MJnGO1IdRluO0OLWILDwxwIfit0VVjFOaw2d3VM1xmA7cYAaSv+Sauw8E2MUgXqXDmkcXRws=
  # DOCKER_PASSWORD
  - secure: hmFUa0ZC3fPbbf2umWPWYY58n/ABXg2JDO/Mr8BK6hYgLcC2+G5jOJfyxvbXNc/VI4Xb/ErsmX7auZhxIOxbzArjiXGQSVs5j1ocWKrf/Cdl5sdtVIOG2LXBqxAxqGp8pcQEgIDjHjeegJ5rKMGyPpGbpHi9m2MeP1oALWU2qzi2F6FW97ZhMPN0G40kjs9ZLEiWo9WffokH5dwubm/4sXgsfSK+TY2EPh4A3O6MV6FoZ8/0l7MFJ61TT6hzo3Rr913DobWop5rJeap71618+YmhDzgcDaerwyag8jXjGDlJvtiYEMVpdAPsXkcEvk2qBiIMM4e5KPdnS+M61ktn7Q10y1Y0E/U3Yo6mzFPSYkoRa68LZ0G9XIgANs+i42+k6wCEi4UZMIxKv0fn3Gkg0LvibFYBbczKavCSRJOWFXzgv4pxdZVLDQPSlyI0lx+lMdL/yeaScFOuTzQsCLUBPggFebXWmiKGNKjvcGEWf/R7lbnfZ60FedeSEShnrUA/iPQNyfQ9mOoXSLOpttFenhrkZbYSEGHt7QbU7lVY7/96XmW2zzmeU0zNP9/Da7p3yj0PGgLtkBI1+wK7k0JLXueeLLHIXxBaYn7loTxCPHTT1tMck6Dp/d1/gGlp4omzV8H2MoV0fxeynWNNdNyCGVLkz7zfeqNM3Be4JbgEEc0=
  # AZURE_STORAGE_CONNECTION_STRING
  - secure: UGOxCb4TepJzterZ7K297+xZxfZC23nU7iWUhBZVV9LgOczraK6nC5r35+EADVtVsEevgHnatAj771BVtA3tiN1cQzx0CrtYhdoUfTDb5Zs+G+Kf9NEHsn7+3RJVDllUP/FknYOzAiwpzdZ8YpHTmz+SdiVDNp9T6LxpWOHf1xdhGNIfbmq+UV8dHGirhnqj5G5S7oMxgkQLsb7/LAzmzOg5ZEWYxi18si4TNdmpHlBp2iykHvNxpURDZkmxHCghd52iQDMGUScYo76wjRDhUQenoVlVCD2xIO9eb6j/tGgt/+fAEnuTK6lkikoQrA+qsSgSB7NM0H/ruvkGKmqEVEXX/CADmKMlnekSEz4zb2ggJSeBDmYXPQsUg67NkpNnYgLQ4UtWGWUxlDws24cEsv5VeVIWhaFouSzA/RgykDhKw01ztZsnveeqTgBLvPFcjCWSNBICBAc+VD/CJn27qyJSkZjSkuRCbRL8tcJ2SCcHZsmRu5v0MphTBS8UcrgrNhCp/75HAuGMTLjTvkdHzcfVJtGl9yPOan0zGeZ5cXQbKt4jNyT9aDgH6HKoh4jgwde+5lBufE5t9qhHeccMIrhbRld9EbkE5xxRFRkE7iwGM6twALNb+bPnMBF4eja0xhdhtwUhrKjT6BqOAyNDXiOvbPVA0jNoaD/KXOzuir4=
script:
- make build test-unit
deploy:
  provider: script
  script: make release
  on:
    branch: master
